### ISSUE TITLE
python manage.py downloadnetfilerawdata fails

### ISSUE THREAD

**Issue by mikeubell** [caciviclab/disclosure-backend#111]
After pulling the latest repo (but it was happening before that), dropping and recreating callaccess_raw then running 'python manage.py downloadnetfilerawdata' eventually ends with:

Loading Agency CSV file
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/ubell/disclosure-backend/env/lib/python2.7/site-packages/django/core/management/**init**.py", line 338, in execute_from_command_line
    utility.execute()
  File "/Users/ubell/disclosure-backend/env/lib/python2.7/site-packages/django/core/management/**init**.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/ubell/disclosure-backend/env/lib/python2.7/site-packages/django/core/management/base.py", line 390, in run_from_argv
    self.execute(_args, *_cmd_options)
  File "/Users/ubell/disclosure-backend/env/lib/python2.7/site-packages/django/core/management/base.py", line 441, in execute
    output = self.handle(_args, *_options)
  File "/Users/ubell/disclosure-backend/netfile/management/commands/downloadnetfilerawdata.py", line 152, in handle
    self.load()
  File "/Users/ubell/disclosure-backend/netfile/management/commands/downloadnetfilerawdata.py", line 219, in load
    super(Command, self).load('NetFileAgency')
  File "/Users/ubell/disclosure-backend/env/src/django-calaccess-raw-data/calaccess_raw/management/commands/loadcalaccessrawfile.py", line 50, in load
    model = get_model(app, model_name)
  File "/Users/ubell/disclosure-backend/env/lib/python2.7/site-packages/django/apps/registry.py", line 202, in get_model
    return self.get_app_config(app_label).get_model(model_name.lower())
  File "/Users/ubell/disclosure-backend/env/lib/python2.7/site-packages/django/apps/config.py", line 162, in get_model
    "App '%s' doesn't have a '%s' model." % (self.label, model_name))
LookupError: App 'calaccess_raw' doesn't have a 'netfileagency' model.

**Comment by bcipolli** [comment]
@mikeubell Just to check: have you run the database migrations, via `python manage.py migrate`? IIRC, I get that error if I haven't done that.

**Comment by mikeubell** [comment]
I did migrate.

**Comment by mikeubell** [comment]
Needed to run pip install -r requirements.txt
