### ISSUE TITLE
netfile: No Data

### ISSUE THREAD

**Issue by mikeubell** [caciviclab/disclosure-backend#112]
I have done the following steps:
535  pip install -r requirements.txt
  536  pip install -r requirements_dev.txt
  537  python manage.py migrate
  538  python manage.py test
  540  python manage.py downloadnetfilerawdata

ALL files report "No data" and there is very little data loaded.
The csv files have data.

**Comment by bcipolli** [comment]
I'll take a look at this.

**Comment by bcipolli** [comment]
@mikeubell I'm not able to reproduce this error. The only error I see is that `netfile_agency.csv` is saved to the wrong directory, but things load just fine to me.

Can you try running with a subset of the data?
`python manage.py downloadnetfilerawdata --agencies ANA`

**Comment by mikeubell** [comment]
The problem is that if the cvs files are there but there is no data in the database, nothing gets loaded.

**Comment by bcipolli** [comment]
Again, I wasn't able to reproduce this issue. I cloned the repo from scratch and ran the commands exactly as you said... the data were all there for me.

**Comment by mikeubell** [comment]
Drop and recreate the database then run the load.  All files report “No data”.

**Comment by adborden** [comment]
@mikeubell I think what you're seeing is fixed by https://github.com/caciviclab/disclosure-backend/pull/122

Can you try again from master?

**Comment by mikeubell** [comment]
I pulled and ran it again and it failed with:
IOError: [Errno 2] No such file or directory: u'/Users/ubell/disclosure-backend/disclosure/../data/calaccess/csv/netfile_agency.csv'

**Comment by bcipolli** [comment]
@mikeubell Can you give some more details:
- Is this after all files were downloaded?
- Can you copy/paste the entire call stack? I need to know where the error occurred, not just what the error was.

Thanks!

Note: I was able to start the download:
![image](https://cloud.githubusercontent.com/assets/4072455/12223878/ec964ab0-b797-11e5-8e95-5c5df3acd33e.png)

I can see that the path in yours looks strange. Netfile data should be in the `data/csv/netfile` directory; yours indicates `data/csv/calaccess`. So I know the issue, I just need to know where/when it's happening.

**Comment by bcipolli** [comment]
Note that I am getting data where data is available; it's not all `No data` for me. Are you still seeing that @mikeubell ?:
![image](https://cloud.githubusercontent.com/assets/4072455/12223901/7daeab00-b798-11e5-8cad-1c52e9198d16.png)

**Comment by mikeubell** [comment]
Sorry, I thought that was already in the issue, but I think I previously sent it directly:
Combining 136 csv files.
Loading Agency CSV file
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/ubell/disclosure-backend/env/lib/python2.7/site-packages/django/core/management/**init**.py", line 338, in execute_from_command_line
    utility.execute()
  File "/Users/ubell/disclosure-backend/env/lib/python2.7/site-packages/django/core/management/**init**.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/ubell/disclosure-backend/env/lib/python2.7/site-packages/django/core/management/base.py", line 390, in run_from_argv
    self.execute(_args, *_cmd_options)
  File "/Users/ubell/disclosure-backend/env/lib/python2.7/site-packages/django/core/management/base.py", line 441, in execute
    output = self.handle(_args, *_options)
  File "/Users/ubell/disclosure-backend/netfile_raw/management/commands/downloadnetfilerawdata.py", line 173, in handle
    self.load()
  File "/Users/ubell/disclosure-backend/netfile_raw/management/commands/downloadnetfilerawdata.py", line 248, in load
    super(Command, self).load('NetFileAgency')
  File "/Users/ubell/disclosure-backend/env/src/django-calaccess-raw-data/calaccess_raw/management/commands/loadcalaccessrawfile.py", line 61, in load
    self.load_mysql(model, csv_path)
  File "/Users/ubell/disclosure-backend/env/src/django-calaccess-raw-data/calaccess_raw/management/commands/loadcalaccessrawfile.py", line 118, in load_mysql
    csv_headers = self.get_headers(csv_path)
  File "/Users/ubell/disclosure-backend/env/src/django-calaccess-raw-data/calaccess_raw/management/commands/loadcalaccessrawfile.py", line 181, in get_headers
    with open(csv_path, 'r') as infile:
IOError: [Errno 2] No such file or directory: u'/Users/ubell/disclosure-backend/disclosure/../data/calaccess/csv/netfile_agency.csv'

This happened even after moving the data directory.

**Comment by bcipolli** [comment]
Thanks. This may be related to #127 . I will have time to check this out in a couple of hours.

**Comment by mikeubell** [comment]
I got a good download from an empty data/ directory and database.
Dropping the database and recreating and then doing the download results in:
(env)ubell@MacBook-Pro ~/disclosure-backend » python manage.py downloadnetfilerawdata
Downloading raw data files
Found 68 agencies
Downloading data for 68 agencies in years 2014,2015
Combining 136 csv files.
Loading Agency CSV file
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/ubell/disclosure-backend/env/lib/python2.7/site-packages/django/core/management/**init**.py", line 338, in execute_from_command_line
    utility.execute()
  File "/Users/ubell/disclosure-backend/env/lib/python2.7/site-packages/django/core/management/**init**.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/ubell/disclosure-backend/env/lib/python2.7/site-packages/django/core/management/base.py", line 390, in run_from_argv
    self.execute(_args, *_cmd_options)
  File "/Users/ubell/disclosure-backend/env/lib/python2.7/site-packages/django/core/management/base.py", line 441, in execute
    output = self.handle(_args, *_options)
  File "/Users/ubell/disclosure-backend/netfile_raw/management/commands/downloadnetfilerawdata.py", line 174, in handle
    self.load()
  File "/Users/ubell/disclosure-backend/netfile_raw/management/commands/downloadnetfilerawdata.py", line 250, in load
    'NetFileAgency', csv_path=self.agency_csv_path)
  File "/Users/ubell/disclosure-backend/env/src/django-calaccess-raw-data/calaccess_raw/management/commands/loadcalaccessrawfile.py", line 60, in load
    self.load_mysql(model, csv_path)
  File "/Users/ubell/disclosure-backend/env/src/django-calaccess-raw-data/calaccess_raw/management/commands/loadcalaccessrawfile.py", line 100, in load_mysql
    self.cursor.execute('TRUNCATE TABLE %s' % model._meta.db_table)
  File "/Users/ubell/disclosure-backend/env/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Users/ubell/disclosure-backend/env/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/ubell/disclosure-backend/env/lib/python2.7/site-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/ubell/disclosure-backend/env/lib/python2.7/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
  File "/Users/ubell/disclosure-backend/env/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/Users/ubell/disclosure-backend/env/lib/python2.7/site-packages/MySQLdb/cursors.py", line 220, in execute
    self.errorhandler(self, exc, value)
  File "/Users/ubell/disclosure-backend/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorvalue
django.db.utils.ProgrammingError: (1146, "Table 'calaccess_raw.netfile_agency' doesn't exist")

**Comment by bcipolli** [comment]
Did you run `python manage.py migrate` after dropping the db and before running the command?

**Comment by mikeubell** [comment]
DOH!

**Comment by mikeubell** [comment]
Sorry, things look good.  Was multitasking this morning.

**Comment by bcipolli** [comment]
Haha after all the pain I've put you through to find and fix this, I think there's plenty more room for pilot error on your side :) Glad to hear things are working, and can't wait to get you onto some of the latest code!
