### ISSUE TITLE
possible path problem with netfile imports

### ISSUE THREAD

**Issue by rkiddy** [caciviclab/disclosure-backend#131]
I am updating things and seeing where things are. The setup is good so far, but when I run the netfile import, I see a problem.

```
 (venv) $ python manage.py downloadnetfilerawdata
 Downloading raw data files
 Found 68 agencies
 Downloading data for 68 agencies in years 2014,2015
 Combining 136 csv files.
 Loading Agency CSV file
 Traceback (most recent call last):
   File "manage.py", line 11, in <module>
     execute_from_command_line(sys.argv)
   File "/Users/rkiddy/Projects/openCA/disclosure-backend/venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
     utility.execute()
   File "/Users/rkiddy/Projects/openCA/disclosure-backend/venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
     self.fetch_command(subcommand).run_from_argv(self.argv)
   File "/Users/rkiddy/Projects/openCA/disclosure-backend/venv/lib/python2.7/site-packages/django/core/management/base.py", line 390, in run_from_argv
     self.execute(*args, **cmd_options)
   File "/Users/rkiddy/Projects/openCA/disclosure-backend/venv/lib/python2.7/site-packages/django/core/management/base.py", line 441, in execute
     output = self.handle(*args, **options)
   File "/Users/rkiddy/Projects/openCA/disclosure-backend/netfile_raw/management/commands/downloadnetfilerawdata.py", line 173, in handle
     self.load()
   File "/Users/rkiddy/Projects/openCA/disclosure-backend/netfile_raw/management/commands/downloadnetfilerawdata.py", line 248, in load
     super(Command, self).load('NetFileAgency')
   File "/Users/rkiddy/Projects/openCA/disclosure-backend/venv/src/django-calaccess-raw-data/calaccess_raw/management/commands/loadcalaccessrawfile.py", line 61, in load
     self.load_mysql(model, csv_path)
   File "/Users/rkiddy/Projects/openCA/disclosure-backend/venv/src/django-calaccess-raw-data/calaccess_raw/management/commands/loadcalaccessrawfile.py", line 118, in load_mysql
     csv_headers = self.get_headers(csv_path)
   File "/Users/rkiddy/Projects/openCA/disclosure-backend/venv/src/django-calaccess-raw-data/calaccess_raw/management/commands/loadcalaccessrawfile.py", line 181, in get_headers
     with open(csv_path, 'r') as infile:
 IOError: [Errno 2] No such file or directory: u'/Users/rkiddy/Projects/openCA/disclosure-backend/disclosure/../data/calaccess/csv/netfile_agency.csv'

 (venv) $ find * -name netfile_agency.csv
 data/netfile/csv/netfile_agency.csv
 (venv) $
```

It looks as though the file is being looked for in data/calaccess/csv and the file is actually located in data/netfile/csv.

**Comment by bcipolli** [comment]
With the latest update, you'll need to re-run `pip install -r requirements.txt`. Can you verify that you did that?

**Comment by rkiddy** [comment]
I could not re-run the requirements fetch. I got different, weirder errors. But enough things had changed that I thought it would worth it to start anew.

When I did this, things seem to work fine.

Some of the netfile fetches give a "No data" message, but I assume that it known and may not be an error.
