### ISSUE TITLE
error from trying to download calaccess data

### ISSUE THREAD

**Issue by rkiddy** [caciviclab/disclosure-backend#135]
I am sorry if I am catching things while things are up in the air. If you all want me to back off for a little while, that would be fine. Otherwise, I am seeing what I am seeing.

```
 $ python manage.py downloadcalaccessrawdata
 Traceback (most recent call last):
   File "manage.py", line 11, in <module>
     execute_from_command_line(sys.argv)
   File "/Users/rkiddy/Projects/openCA/disclosure-backend/venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
     utility.execute()
   File "/Users/rkiddy/Projects/openCA/disclosure-backend/venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
     self.fetch_command(subcommand).run_from_argv(self.argv)
   File "/Users/rkiddy/Projects/openCA/disclosure-backend/venv/lib/python2.7/site-packages/django/core/management/base.py", line 390, in run_from_argv
     self.execute(*args, **cmd_options)
   File "/Users/rkiddy/Projects/openCA/disclosure-backend/venv/lib/python2.7/site-packages/django/core/management/base.py", line 441, in execute
     output = self.handle(*args, **options)
   File "/Users/rkiddy/Projects/openCA/disclosure-backend/venv/src/django-calaccess-raw-data/calaccess_raw/management/commands/downloadcalaccessrawdata.py", line 140, in handle
     self.set_options(*args, **options)
   File "/Users/rkiddy/Projects/openCA/disclosure-backend/venv/src/django-calaccess-raw-data/calaccess_raw/management/commands/downloadcalaccessrawdata.py", line 120, in set_options
     prompt_context,
   File "/Users/rkiddy/Projects/openCA/disclosure-backend/venv/lib/python2.7/site-packages/django/template/loader.py", line 99, in render_to_string
     return template.render(context, request)
   File "/Users/rkiddy/Projects/openCA/disclosure-backend/venv/lib/python2.7/site-packages/django/template/backends/django.py", line 74, in render
     return self.template.render(context)
   File "/Users/rkiddy/Projects/openCA/disclosure-backend/venv/lib/python2.7/site-packages/django/template/base.py", line 209, in render
     return self._render(context)
   File "/Users/rkiddy/Projects/openCA/disclosure-backend/venv/lib/python2.7/site-packages/django/template/base.py", line 201, in _render
     return self.nodelist.render(context)
   File "/Users/rkiddy/Projects/openCA/disclosure-backend/venv/lib/python2.7/site-packages/django/template/base.py", line 903, in render
     bit = self.render_node(node, context)
   File "/Users/rkiddy/Projects/openCA/disclosure-backend/venv/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
     return node.render(context)
   File "/Users/rkiddy/Projects/openCA/disclosure-backend/venv/lib/python2.7/site-packages/django/template/debug.py", line 89, in render
     output = self.filter_expression.resolve(context)
   File "/Users/rkiddy/Projects/openCA/disclosure-backend/venv/lib/python2.7/site-packages/django/template/base.py", line 674, in resolve
     new_obj = func(obj, *arg_vals)
   File "/Users/rkiddy/Projects/openCA/disclosure-backend/venv/lib/python2.7/site-packages/django/template/defaultfilters.py", line 771, in date
     return formats.date_format(value, arg)
   File "/Users/rkiddy/Projects/openCA/disclosure-backend/venv/lib/python2.7/site-packages/django/utils/formats.py", line 136, in date_format
     return dateformat.format(value, get_format(format or 'DATE_FORMAT', use_l10n=use_l10n))
   File "/Users/rkiddy/Projects/openCA/disclosure-backend/venv/lib/python2.7/site-packages/django/utils/formats.py", line 110, in get_format
     for module in get_format_modules(lang):
   File "/Users/rkiddy/Projects/openCA/disclosure-backend/venv/lib/python2.7/site-packages/django/utils/formats.py", line 82, in get_format_modules
     modules = _format_modules_cache.setdefault(lang, list(iter_format_modules(lang, settings.FORMAT_MODULE_PATH)))
   File "/Users/rkiddy/Projects/openCA/disclosure-backend/venv/lib/python2.7/site-packages/django/utils/formats.py", line 51, in iter_format_modules
     if not check_for_language(lang):
   File "/Users/rkiddy/Projects/openCA/disclosure-backend/venv/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 181, in check_for_language
     return _trans.check_for_language(lang_code)
   File "/Users/rkiddy/Projects/openCA/disclosure-backend/venv/lib/python2.7/site-packages/django/utils/lru_cache.py", line 125, in wrapper
     result = user_function(*args, **kwds)
   File "/Users/rkiddy/Projects/openCA/disclosure-backend/venv/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 409, in check_for_language
     if not language_code_re.search(lang_code):
 TypeError: expected string or buffer
 (venv)~/Projects/openCA/disclosure-backend$ 
```

**Comment by bcipolli** [comment]
Cool with me. This looks like a config issue. Did you set up a `settings_local.py`? Can you confirm that you followed all the installation steps, including the migrations, outlined in the `README.md` file?

**Comment by rkiddy** [comment]
Yep. I got this out my history:

```
   503  virtualenv venv
   504  source venv/bin/activate
   505  pip install -r requirements.txt
   506  pip install -r requirements_dev.txt
   507  vi disclosure/settings.py 
   508  python manage.py migrate # oops. the opendisclosure databbase is new.
   509  mysql
   510  python manage.py migrate
   511  python manage.py migrate --database calaccess_raw # oops. Is there more than one...
   513  grep -r root * | grep settings
   514  vi disclosure/settings.py # changing the 2nd USER and PASSWORD....
   515  python manage.py migrate --database calaccess_raw
   516  python manage.py downloadzipcodedata
   517  python manage.py downloadnetfilerawdata
   518  python manage.py downloadcalaccessrawdata
```

**Comment by bcipolli** [comment]
Ah, ok, I remember now--this is a duplicate of https://github.com/caciviclab/disclosure-backend/issues/90 . 

I just merged a fix; can you pull the latest code and retry? Just need to `pip install -r requirements.txt`

**Comment by rkiddy** [comment]
And it works. At some point, I will get past finding dupes. It is hard to avoid doign this occiasionally, though.

**Comment by bcipolli** [comment]
Glad that it works. No worries! I mean goodness, I opened that issue and it even took me a while to find it :P
