### ISSUE TITLE
downloadnetfilerawdata with --skip-download crashes

### ISSUE THREAD

**Issue by adborden** [caciviclab/disclosure-backend#142]
```
backend@opencal:~$ PATH=/data/backend/env/bin:$PATH python /data/backend/current/manage.py downloadnetfilerawdata --skip-download --no-color  --verbosity=3
Traceback (most recent call last):
  File "/data/backend/current/manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/data/backend/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/data/backend/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/data/backend/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 390, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/data/backend/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 441, in execute
    output = self.handle(*args, **options)
  File "/data/backend/1453089877/netfile_raw/management/commands/downloadnetfilerawdata.py", line 171, in handle
    self.combine()
  File "/data/backend/1453089877/netfile_raw/management/commands/downloadnetfilerawdata.py", line 225, in combine
    self.header("Combining %s csv files." % len(self.csv_paths))
AttributeError: 'Command' object has no attribute 'csv_paths'
```

**Comment by bcipolli** [comment]
:+1: and indicates some useful tests to add. Cool!
