### ISSUE TITLE
Can't import zipcode data

### ISSUE THREAD

**Issue by adborden** [caciviclab/disclosure-backend#30]
```
$ python disclosure-backend/manage.py downloadzipcodedata
Downloading/unzipping raw data files
ok.
Loading CSV files
Traceback (most recent call last):
  File "disclosure-backend/manage.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/home/adborden/.virtualenvs/disclosure-backend/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/adborden/.virtualenvs/disclosure-backend/lib/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/adborden/.virtualenvs/disclosure-backend/lib/python2.7/site-packages/django/core/management/base.py", line 393, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/adborden/.virtualenvs/disclosure-backend/lib/python2.7/site-packages/django/core/management/base.py", line 444, in execute
    output = self.handle(*args, **options)
  File "zipcode_metro/management/commands/downloadzipcodedata.py", line 49, in handle
    self.load()
  File "zipcode_metro/management/commands/downloadzipcodedata.py", line 73, in load
    super(Command, self).load('zipcode_metro.ZipCodeMetro')
  File "/home/adborden/.virtualenvs/disclosure-backend/src/django-calaccess-raw-data/calaccess_raw/management/commands/loadcalaccessrawfile.py", line 33, in load
    model = get_model("calaccess_raw", model_name)
  File "/home/adborden/.virtualenvs/disclosure-backend/lib/python2.7/site-packages/django/apps/registry.py", line 202, in get_model
    return self.get_app_config(app_label).get_model(model_name.lower())
  File "/home/adborden/.virtualenvs/disclosure-backend/lib/python2.7/site-packages/django/apps/config.py", line 162, in get_model
    "App '%s' doesn't have a '%s' model." % (self.label, model_name))
LookupError: App 'calaccess_raw' doesn't have a 'zipcode_metro.zipcodemetro' model.
```

**Comment by adborden** [comment]
@seanius can you take a look at this? seems like with calaccess_raw installed as a dependency, python isn't looking at our project for the path to `zipcode_metro`.
